language: java
jdk:
    - oraclejdk8
before_install: "git clone -b travis-ci-settings `git config --get remote.origin.url` travis"
script:
    - "mvn test -B"
    - "./run-sonar.sh"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e74e6730e58edfde1d39
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
